CREATE TABLE kpi.Project_Kpi(
	Id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	Project_Id INT(10) UNSIGNED NOT NULL,
	Kpi_Id INT(10) UNSIGNED NOT NULL,
	
	PRIMARY KEY (Id),
	FOREIGN KEY (Project_Id) REFERENCES Project(Id) ON DELETE CASCADE,
	FOREIGN KEY (Kpi_Id) REFERENCES Kpi(Id) ON DELETE CASCADE
);